// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-RWPH9tc1G9cfAlKerWFP13xrppeqUzs',
    appId: '1:870609341728:web:ea1fea778b54d9902f5b45',
    messagingSenderId: '870609341728',
    projectId: 'nbank-16aeb',
    authDomain: 'nbank-16aeb.firebaseapp.com',
    storageBucket: 'nbank-16aeb.firebasestorage.app',
    measurementId: 'G-YGF877JYC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnff7YsLRg6ppMpifCcMXHRBnGfNKmnMo',
    appId: '1:870609341728:android:28f14d8ef0d6f6be2f5b45',
    messagingSenderId: '870609341728',
    projectId: 'nbank-16aeb',
    storageBucket: 'nbank-16aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXoiP3eyo35UmZULg00UCtdNyyt75qPks',
    appId: '1:870609341728:ios:8fc4c12418a998122f5b45',
    messagingSenderId: '870609341728',
    projectId: 'nbank-16aeb',
    storageBucket: 'nbank-16aeb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXoiP3eyo35UmZULg00UCtdNyyt75qPks',
    appId: '1:870609341728:ios:8fc4c12418a998122f5b45',
    messagingSenderId: '870609341728',
    projectId: 'nbank-16aeb',
    storageBucket: 'nbank-16aeb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-RWPH9tc1G9cfAlKerWFP13xrppeqUzs',
    appId: '1:870609341728:web:cb4ea9fd1d9da20d2f5b45',
    messagingSenderId: '870609341728',
    projectId: 'nbank-16aeb',
    authDomain: 'nbank-16aeb.firebaseapp.com',
    storageBucket: 'nbank-16aeb.firebasestorage.app',
    measurementId: 'G-MQVPKE20R2',
  );
}
